// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taokoaezxhwfapvzzmfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhb2tvYWV6eGh3ZmFwdnp6bWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDk1MTgsImV4cCI6MjA3MjQ4NTUxOH0.NrH97bnvh97WJzW2g4Ba6XK9uTakldHHP-p0owOzgQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});